[versions]

agp = "8.5.2"
kotlin = "2.1.20"
koin = "4.1.0"
android-appcompat = "1.7.1"

[libraries]
android-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
